# Generated by Django 5.1.5 on 2025-05-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
