# Generated by Django 5.1.5 on 2025-05-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bus_friday_bus_monday_bus_saturday_bus_sunday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
        migrations.AddField(
            model_name='bus',
            name='friday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='monday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='saturday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='sunday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='thursday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='tuesday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='wednesday_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
