# Generated by Django 5.1.5 on 2025-05-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_bus_date_remove_bus_time_bus_friday_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='bus',
            name='friday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='monday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='saturday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='sunday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='thursday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='tuesday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='wednesday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
